language: java
jdk:
  - openjdk11

branches:
  only:
    - master

# Travis CI 서버의 HOME
cache:
  directories:
    - '$HOME/.me/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notification:
  email:
    recipents:
      - jhl81094@gmail.com
