language: java
jdk:
  - openjdk11

branches:
  only:
    - main

cache:
  directories:
    - '$HOME/.me/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

notification:
  email:
    recipents:
      - jhl81094@gmail.com
